// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An expert AI responder agent.
 *
 * - respond - A function that handles the initial response generation.
 * - RespondInput - The input type for the respond function.
 * - RespondOutput - The return type for the respond function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RespondInputSchema = z.object({
  query: z.string().describe('The question to be answered.'),
});
export type RespondInput = z.infer<typeof RespondInputSchema>;

const RespondOutputSchema = z.object({
  answer: z.string().describe('A comprehensive, well-reasoned answer to the question.'),
});
export type RespondOutput = z.infer<typeof RespondOutputSchema>;

export async function respond(input: RespondInput): Promise<RespondOutput> {
  return respondFlow(input);
}

const prompt = ai.definePrompt({
  name: 'respondPrompt',
  input: {schema: RespondInputSchema},
  output: {schema: RespondOutputSchema},
  prompt: `You are an expert responder agent in a critical thinking system. 
Provide a comprehensive, well-reasoned answer to this question: "{{{query}}}"

Your response should be:
- Thorough but concise (2-3 paragraphs)
- Based on established knowledge
- Clear and well-structured
- Confident but not overreaching

Focus on accuracy and clarity. This is the initial response that will be analyzed by other agents.`,
});

const respondFlow = ai.defineFlow(
  {
    name: 'respondFlow',
    inputSchema: RespondInputSchema,
    outputSchema: RespondOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return {
      answer: output!.answer,
    };
  }
);
